---
site_name: IrishLab.io Documentation
site_description: Documentation for the IrishLab.io organization, covering project overview, architecture, development, pipeline, security, and testing.
site_author: irish1986

docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - footnotes:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: README.md
  - Context: context.md
  - Organization:
      - Setup Overview: organization/overview.md
      - Bootstrap Checklist: organization/bootstrap-checklist.md
      - Policy Template: organization/policy-template.md
  - Architecture:
      - Overview: architecture/overview.md
  - Development:
      - Overview: development/overview.md
  - Pipeline:
      - Overview: pipeline/overview.md
      - Branches: pipeline/branches.md
      - Dependabot: pipeline/dependabot.md
      - Terraform: pipeline/terraform.md
      - Renovate: pipeline/renovate.md
      - MkDocs to Cloudflare Pages: pipeline/mkdocs-cloudflare.md
      - Repository Request (Issue to PR): pipeline/repo-request-issue.md
      - Reusable Workflows:
          - Ansible Lint: pipeline/reusable-ansible-lint.md
          - Bitwarden Secret Deploy: pipeline/reusable-bitwarden-secret-deploy.md
          - Bitwarden Secret Sync: pipeline/reusable-bitwarden-secret.md
          - Docker Build and Push: pipeline/reusable-docker-build.md
          - GH Labeler: pipeline/reusable-gh-labeler.md
          - Ensure SHA Pinned Actions: pipeline/reusable-gh-pin-actions.md
          - GitGuardian Secret Scan: pipeline/reusable-gitguardian.md
          - Hello World: pipeline/reusable-hello-world.md
          - Trivy Image Scan: pipeline/reusable-image-scan.md
          - Pre-Commit: pipeline/reusable-pre-commit.md
          - Prek: pipeline/reusable-prek.md
          - Python UV: pipeline/reusable-python-uv.md
          - SAST: pipeline/reusable-sast.md
          - Secret Scan: pipeline/reusable-secret.md
          - Snyk: pipeline/reusable-snyk.md
          - SonarQube: pipeline/reusable-sonarqube.md
          - Sync Label: pipeline/reusable-sync-label.md
          - Tailscale: pipeline/reusable-tailscale.md
  - Security:
      - Overview: security/overview.md
  - Testing:
      - Overview: testing/overview.md
