blank_issues_enabled: true
contact_links:
  - name: Community and Social
    url: admin@irishlab.io
    about: Please contact us if you have any questions aad want to learn more about our work or how to contribute.
