---
name: CI - Cron

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '32 6 * * *' # set random cron
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  harden-runner:
    name: Call Harden Runner
    uses: irishlab-io/.github/.github/workflows/reusable-harden-runner.yml@main

    permissions:
      contents: read

  pre-commit:
    name: Call Pre-Commit run
    uses: irishlab-io/.github/.github/workflows/reusable-pre-commit.yml@main

  secret:
    needs:
      - pre-commit
    name: Call Secret Scanning
    uses: irishlab-io/.github/.github/workflows/reusable-secret.yml@main
    secrets: inherit
