---
name: CI - Cron

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '32 6 * * *' # set random cron
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Secret Scanning
    uses: irishlab-io/.github/.github/workflows/reusable-secret.yml@main
    secrets: inherit
