---
name: CI - Cron
run-name: Continuous Integration on ${{ github.head_ref || github.ref_name }} by ${{ github.actor }}

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '32 6 * * *' # set random cron
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Call Prek
    uses: irishlab-io/.github/.github/workflows/reusable-prek.yml@main
    with:
      skips: "actionlint,ggshield,pin-github-action"

  secret:
    needs:
      - pre-commit
    name: Call Git Guardian
    uses: irishlab-io/.github/.github/workflows/reusable-gitguardian.yml@main
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
