---
name: CI - Main

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ENVIRONMENT: "prod"

jobs:

  pre-commitk:
    name: Call Prek
    id: pre-commit
    uses: irishlab-io/.github/.github/workflows/reusable-prek.yml@main
    with:
      skip: "pin-github-action"

  secret:
    needs:
      - pre-commit
    name: Call Git Guardian
    id: secret
    uses: irishlab-io/.github/.github/workflows/reusable-gitguardian.yml@main
    secrets: inherit
