---
name: CI - Main
run-name: Continuous Integration on branch ${{ github.head_ref || github.ref_name }} by ${{ github.actor }}

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ENVIRONMENT: "prod"

jobs:

  pre-commit:
    name: Call Prek
    uses: irishlab-io/.github/.github/workflows/reusable-prek.yml@main
    with:
      skips: "actionlint,ggshield,pin-github-action"

  secret:
    needs:
      - pre-commit
    name: Call Git Guardian
    uses: irishlab-io/.github/.github/workflows/reusable-gitguardian.yml@main
    secrets: inherit
