---
name: CI - Main

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Call Pre-Commit run
    uses: irishlab-io/.github/.github/workflows/reusable-pre-commit.yml@main

  secret:
    needs:
      - pre-commit
    name: Call Secret Scanning
    uses: irishlab-io/.github/.github/workflows/reusable-secret.yml@main
    secrets: inherit

  ansible:
    name: Call Ansible Lint
    uses: irishlab-io/.github/.github/workflows/reusable-hello-world.yml@main

    needs:
      - pre-commit
      - secret

  docker-build:
    name: Call Docker Build
    uses: irishlab-io/.github/.github/workflows/reusable-docker-build.yml@main

    needs:
      - pre-commit
      - secret

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      context: "./demo/docker/"
      image-names: |
        ghcr.io/irishlab-io/demo-docker
      platforms: |
          linux/amd64
          linux/arm64
      push: false

  python-uv:
    name: Run Unit Tests & Integration Tests
    uses: irishlab-io/.github/.github/workflows/reusable-python-uv.yml@main

    with:
      working_directory: "demo/python"

    needs:
      - secret
      - sca
      - sast

  sca:
    needs:
      - pre-commit
    name: Placeholder - Software Composition Analysis
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:

      - name: Run SCA
        run: echo Software Composition Analysis
        shell: bash

  sast:
    needs:
      - pre-commit
    name: Call Static Application Security Testing
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:

      - name: Run SAST
        run: echo Static Application Security Testing
        shell: bash
