---
name: CI - Repository

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pinned-actions:
    name: Call Ensure SHA Pinned Actions
    uses: irishlab-io/.github/.github/workflows/reusable-ensure-pin-actions.yml@main
