---
name: Reusable - Prek


on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      skips:
        description: Prek Skip
        required: false
        type: string

jobs:
  prek:
    name: Run prek
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Prek Checks
        id: precommit
        uses: j178/prek-action@53276d8b0d10f8b6672aa85b4588c6921d0370cc # v2.0.1
        env:
          SKIP: ${{ inputs.skips }}
        continue-on-error: true

      - name: Check status of potentially failing step and issue warning
        if: steps.precommit.outcome == 'failure'
        run: |
          echo "::error::The previous step detected potential pre-commit issues in the code. Please review the CI report above."
        shell: bash
