---
name: Reusable - Run Sonarqube Scan

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      gating:
        description: Enable Sonarqube Quality Gate
        required: false
        type: boolean
        default: true
    secrets:
      TS_OAUTH_CLIENT_ID:
        description: Tailscale OAuth client ID
        required: true
      TS_OAUTH_CLIENT_SECRET:
        description: Tailscale OAuth client secret
        required: true
      SONARQUBE_TOKEN:
        description: SonarQube Token
        required: true
      SONARQUBE_URL:
        description: SonarQube Host URL
        required: true

jobs:
  sonarqube:
    name: Sonarqube Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Call Tailscale Action
        id: tailscale
        uses: irishlab-io/.github/.github/actions/tailscale@main
        with:
          ts-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          ts-client-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: "tag:ci"

      - name: Get Tailscale IP address
        run: |
          tailscale ip -4
        shell: bash

      - name: Run SAST - SonarQube
        uses: SonarSource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf # v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_URL }}

      - name: Quality gating SAST - SonarQube
        if: ${{ inputs.gating }}
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
