---
name: Reusable - Run GitGuardian scan

on: # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      GITGUARDIAN_API_KEY:
        description: Git Guardian API Key
        required: true

jobs:
  secret:
    name: GitGuardian scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: GitGuardian scan
        id: secret
        uses: GitGuardian/ggshield/actions/secret@ca3f7d65b17b7c3dcbec98b870299754adf7ff0e # v1.48.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        continue-on-error: true

      - name: Check status of potentially failing step and issue warning
        if: steps.secret.outcome == 'failure'
        run: |
          echo "::error::The previous step detected potential secrets in the code. Please review the scan report above."
        shell: bash
