---
name: Reusable - Run Static Application Security Testing

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      sonarqube:
        description: Run Sonarqube scan
        required: false
        type: boolean
        default: false
      snyk:
        description: 'Run Snyk scan'
        required: false
        type: boolean
        default: false
    secrets:
      SONAR_TOKEN:
        description: SonarQube Token
        required: false
      SONAR_HOST_URL:
        description: SonarQube Host URL
        required: false
      SNYK_TOKEN:
        description: Snyk Token
        required: false
      TAILSCALE_AUTHKEY:
        description: Tailscale Auth Key
        required: false

jobs:
  sonarqube:
    if: ${{ inputs.sonarqube }}
    name: Call SonarQube Scan
    uses: irishlab-io/.github/.github/workflows/reusable-sonarqube.yml@main

    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

  snyk:
    if: ${{ inputs.snyk }}
    name: Call Snyk Scan
    uses: irishlab-io/.github/.github/workflows/reusable-snyk.yml@main

    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
