---
name: Reusable - Python UV

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      python_file:
        description: Python version to use
        type: string
        required: false
        default: ".python-version"
      uv_version:
        description: UV version to use
        type: string
        required: false
        default: "0.7.11"
      working_directory:
        description: Project working directory
        type: string
        required: false
        default: ""

jobs:
  python-poetry:
    name: Python - UV
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: ${{ inputs.uv_version }}

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5.6.0
        with:
          python-version-file: ${{ inputs.python_file || 'pyproject.toml' }}

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev --frozen

      - name: Test with pytest
        run: |
          uv run pytest

      - name: Minimize uv cache
        run: |
          uv cache prune --ci
