---
name: Reusable - Harden Runner Check


on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      allowlist:
        description: Three rules to (optionally) set for tag-rules, latest, prefix, and suffix
        required: false
        type: string
        default: |
            aws-actions/
            docker/login-action

jobs:
  pinned-actions:
    name: Harden Runner Check

    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Step Security scan

        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
