---
name: Reusable - Prek


on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      skips:
        description: Prek Skip
        required: false
        type: string

jobs:
  prek:
    name: Run prek
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run Prek Checks
        id: precommit
        uses: j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037 # v1.1.1
        env:
          SKIP: ${{ inputs.skips }}
        continue-on-error: true

      - name: Check status of potentially failing step and issue warning
        if: steps.precommit.outcome == 'failure'
        run: |
          echo "::error::The previous step detected potential pre-commit issues in the code. Please review the CI report above."
        shell: bash
