---
name: Reusable - Repository Misconfigurations

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  repo-security:
    name: Run poutine
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: poutine - GitHub Actions SAST
        uses: boostsecurityio/poutine-action@c83aa63812538446b9ee5f17b493a57823c62b91 # main

      - name: Upload poutine SARIF file
        uses: github/codeql-action/upload-sarif@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2
        with:
          sarif_file: results.sarif
