---
name: Reusable - Repository Misconfigurations

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  repo-security:
    name: Run poutine
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: poutine - GitHub Actions SAST
        uses: boostsecurityio/poutine-action@84c0a0d32e8d57ae12651222be1eb15351429228 # v0.15.2

      - name: Upload poutine SARIF file
        uses: github/codeql-action/upload-sarif@39edc492dbe16b1465b0cafca41432d857bdb31a # v3.29.1
        with:
          sarif_file: results.sarif
